'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBCodeStandard.Resources", GetType(Resources).GetTypeInfo.Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calls to the Microsoft.VisualBasic namespace should be avoided whereever possible..
        '''</summary>
        Friend ReadOnly Property AvoidMicrosoftVisualBasicNamespaceAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("AvoidMicrosoftVisualBasicNamespaceAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; is in the Microsoft.VisualBasic namespace.  Please try and replace with a C# compatible method or type..
        '''</summary>
        Friend ReadOnly Property AvoidMicrosoftVisualBasicNamespaceAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("AvoidMicrosoftVisualBasicNamespaceAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Avoid Microsoft.VisualBasic namespace.
        '''</summary>
        Friend ReadOnly Property AvoidMicrosoftVisualBasicNamespaceAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("AvoidMicrosoftVisualBasicNamespaceAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comments must be formatted for readability.
        '''</summary>
        Friend ReadOnly Property CommentFormatAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("CommentFormatAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comment is not formatted correctly: {0}.
        '''</summary>
        Friend ReadOnly Property CommentFormatAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("CommentFormatAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Format comment.
        '''</summary>
        Friend ReadOnly Property CommentFormatRuleAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("CommentFormatRuleAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Where possible use single line if statements as they are easier to read..
        '''</summary>
        Friend ReadOnly Property ConvertToSingleLineIfRuleAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("ConvertToSingleLineIfRuleAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This can be conerted to a single line if..
        '''</summary>
        Friend ReadOnly Property ConvertToSingleLineIfRuleAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("ConvertToSingleLineIfRuleAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert to a single line If.
        '''</summary>
        Friend ReadOnly Property ConvertToSingleLineIfRuleAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("ConvertToSingleLineIfRuleAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vUsing adjHungarian nnotation vmakes nreading ncode adjdifficult..
        '''</summary>
        Friend ReadOnly Property HungarianNotationAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("HungarianNotationAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove the hungarian notation..
        '''</summary>
        Friend ReadOnly Property HungarianNotationAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("HungarianNotationAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hungarian Notation.
        '''</summary>
        Friend ReadOnly Property HungarianNotationAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("HungarianNotationAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parentheses on method calls make them easily destingishable and improves readability of the code..
        '''</summary>
        Friend ReadOnly Property MethodCallMustHaveParenthesesAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("MethodCallMustHaveParenthesesAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Method call lacks parentheses.
        '''</summary>
        Friend ReadOnly Property MethodCallMustHaveParenthesesAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("MethodCallMustHaveParenthesesAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Method call should have parentheses.
        '''</summary>
        Friend ReadOnly Property MethodCallMustHaveParenthesesRuleAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("MethodCallMustHaveParenthesesRuleAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use String.Empty as it is more readable.
        '''</summary>
        Friend ReadOnly Property ReplaceEmptyStringWithStringDotEmptyAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("ReplaceEmptyStringWithStringDotEmptyAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Replace with String.Empty.
        '''</summary>
        Friend ReadOnly Property ReplaceEmptyStringWithStringDotEmptyAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("ReplaceEmptyStringWithStringDotEmptyAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use String.Empty.
        '''</summary>
        Friend ReadOnly Property ReplaceEmptyStringWithStringDotEmptyAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("ReplaceEmptyStringWithStringDotEmptyAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parentheses on complex single line if statements make them easily destingishable and improves readability of the code..
        '''</summary>
        Friend ReadOnly Property SingleLineIfStatementParenthesesAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("SingleLineIfStatementParenthesesAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Single line if is missing parentheses.
        '''</summary>
        Friend ReadOnly Property SingleLineIfStatementParenthesesAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("SingleLineIfStatementParenthesesAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing parantheses in line line if.
        '''</summary>
        Friend ReadOnly Property SingleLineIfStatementParenthesesAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("SingleLineIfStatementParenthesesAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use the String.Equals shared member to compare string.  The method offers overloads to handle casing and culture-aware comparison, and when specified ensures that the string comparison will not change with Option Compare..
        '''</summary>
        Friend ReadOnly Property StringEqualsRuleAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("StringEqualsRuleAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use String.Equals to compare strings. .
        '''</summary>
        Friend ReadOnly Property StringEqualsRuleAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("StringEqualsRuleAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compare strings with String.Equals.
        '''</summary>
        Friend ReadOnly Property StringEqualsRuleAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("StringEqualsRuleAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Single line guard clauses are easier to read..
        '''</summary>
        Friend ReadOnly Property UntidyGuardClauseRuleAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("UntidyGuardClauseRuleAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This can be converted to a single line guard clause.
        '''</summary>
        Friend ReadOnly Property UntidyGuardClauseRuleAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("UntidyGuardClauseRuleAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Untidy guard clause.
        '''</summary>
        Friend ReadOnly Property UntidyGuardClauseRuleAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("UntidyGuardClauseRuleAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ensure value types are not initialised to their default and reference types are assigned a value..
        '''</summary>
        Friend ReadOnly Property VariableDeclarationAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("VariableDeclarationAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable declaration can be improved.
        '''</summary>
        Friend ReadOnly Property VariableDeclarationAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("VariableDeclarationAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable declaration.
        '''</summary>
        Friend ReadOnly Property VariableDeclarationRuleAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("VariableDeclarationRuleAnalyzerTitle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
